services:
  negpy:
    build:
      context: .
      network: host
    container_name: negpy
    ports:
      - "8501:8501"
    volumes:
      - ./:/app
      - ${NEGPY_HOST_DIR}:/app/user
    environment:
      - NEGPY_USER_DIR=user
    restart: unless-stopped